# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kickback' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kickback
  # Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Amplitude-iOS', '~> 3.14.1'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]


  target 'kickbackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
