# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kickback' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kickback
  # Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'kickbackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kickback-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kickback-tvOS

  target 'kickback-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
