# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Kickback' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RSKImageCropper', :git => 'https://github.com/ruslanskorb/RSKImageCropper.git', :branch => 'master'
  pod 'QBImagePickerController'
  # Pods for Kickback

  target 'KickbackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
